# logger configure
[logger]
    # logger level
    level = "debug"
    # log file max size (MB)
    max-size = 100
    # log file save days
    max-age = 15
    # log file max num
    max-backups = 15
    # log file storage dir
    output = "log"
    # enabled stdout
    stdout = true

# network listener configure
[[listener]]
    transport   = "tcp"
    protocol    = "tcp"
    port        = 17000
    size        = 1048
    rtimeout    = 2
    wtimeout    = 2

[[listener]]
    transport   = "udp"
    protocol    = "udp"
    port        = 18000
    size        = 1048
    rtimeout    = 2
    wtimeout    = 2

[[listener]]
    transport   = "udp"
    protocol    = "dns"
    port        = 18053
    size        = 1048
    rtimeout    = 2
    wtimeout    = 2
