# network listener configure
[listener]

    # tcp raw listener
    [listener.tcp]
        host    = "127.0.0.1"
        port    = "17888"

    # udp raw listener
    [listener.udp]
        host    = "127.0.0.1"
        port    = "17889"