# logger configure
[logger]
    # logger level
    level = "debug"
    # log file max size (MB)
    max-size = 100
    # log file save days
    max-age = 15
    # log file max num
    max-backups = 15
    # log file storage dir
    output = "log"
    # enabled stdout
    stdout = true

# network listener configure
[listener]

    # tcp raw listener
    [listener.tcp]
        host    = "127.0.0.1"
        port    = "17888"

    # udp raw listener
    [listener.udp]
        host    = "127.0.0.1"
        port    = "17889"