# logger configure
[logger]
    # logger level
    level = "debug"
    # log file max size (MB)
    max-size = 100
    # log file save days
    max-age = 15
    # log file max num
    max-backups = 15
    # log file storage dir
    output = "log"
    # enabled stdout
    stdout = true

# tls certificate configure
[tls]
    ca      = "../configs/rootCA.crt"
    cert    = "../configs/localhost.crt"
    key     = "../configs/localhost.key"

# dns reslover configure
[reslover]
    dns         = ":15353"
    dnsserver   = ["8.8.8.8"]
    timeout     = 3
    maxTTL      = 1800
    minTTL      = 0
    cache       = 4096

# tunnel forwarder configure
[forwarder]
    mode            = "direct"
    dial-timeout    = 3
    relay-timeout   = 3


# network listener configure
[[listener]]
    transport   = "tcp"
    protocol    = "tcp"
    address     = ":17000"
    size        = 1048
    rtimeout    = 2
    wtimeout    = 2
